{
  "id": "15d5fe5732583e7a",
  "threadId": "15d5fe5732583e7a",
  "mailboxIds": [
    "inbox",
    "important"
  ],
  "isUnread": false,
  "isFlagged": false,
  "isAnswered": true,
  "isDraft": false,
  "hasAttachment": true,
  "headers": {
    "Delivered-To": "christos@redsift.io",
    "Message-Id": "<CAC2uNfU+gXP8C7DXnoTpRiZw+PZXVeK1V=Au9cD1590BkcwoKQ@mail.gmail.com>",
    "Mime-Version": "1.0",
    "Return-Path": "<rois@redsift.io>",
    "X-GM-MSGID": "15d5fe5732583e7a",
    "X-GM-THRID": "15d5fe5732583e7a",
    "X-Gm-Message-State": "AIVw111fIT2IuK/aAc4mrK5Kz8XTLeuS2Jeo1n82+CFiUMmbSwhmffne FWoQ0FmtATAn9utSA/bCs2XrqqlDBxr0gR2qTANE",
    "X-Google-Dkim-Signature": "v=1; a=rsa-sha256; c=relaxed/relaxed; d=1e100.net; s=20161025; h=x-gm-message-state:mime-version:from:date:message-id:subject:to; bh=cUr2lYX6M4JP2Q371fK0p11L50mx864iBbRxoeEQpak=; b=lW2s1sHrRagJZScDUOvuK9VWY3wMFuZCwROqO9ALtZH0h5EM4oom6uzWJghHrkcwEi tELu5P/PxkTgsQDTNA0XIwOgOtC7gmEVzt1Z4U0T13aQyLrAD41yVeuXwP1rUyFCwvci BIJYBYHJxMQuzVz15RUTyqFSICZ1eGmQbHJ8dHGzlXtqlyihqMkDMxcb73DwqgNygYC6 qmGokTYREX/KGyVSN9sW9aMaLHPQV1X5xQ5hWOjHvDxR2YKsdWncJv9MYMOAkFK9O3j5 XlCUuZ7Dma2GOQut5Nj8Y7qIARIzMBOuA47FsxvYLgwI5L55oFDQW5UNX0ugcaRtLFt8 l1gw==",
    "X-Received": "by 10.237.61.146 with SMTP id i18mr4420160qtf.239.1500552458862; Thu, 20 Jul 2017 05:07:38 -0700 (PDT)\nby 10.200.40.137 with SMTP id i9mr4775385qti.274.1500552458030; Thu, 20 Jul 2017 05:07:38 -0700 (PDT)",
    "X-Redsift-Date-Parsing-Result": "pass"
  },
  "from": {
    "name": "Rois Ni Thuama",
    "email": "rois@redsift.io"
  },
  "to": [
    {
      "name": "Christos Vontas",
      "email": "christos@redsift.io"
    }
  ],
  "subject": "please",
  "date": "2017-07-20T13:07:37+01:00",
  "size": 615124,
  "preview": "[image: Inline images 1]  -- Cybersecurity",
  "strippedHtmlBody": "- Cybersecurity governance",
  "user": "christos@redsift.io"
}